version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine3.18
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - "5433:5432"


  app:
    build: .
    container_name: app
    image: app
    env_file:
      - .env.example
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg-data:
