app:
  name: 'go-tg-auth'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-tg-auth'

postgres:
  pool_max: 10
  url: "postgres://user:pass@localhost:5435/postgres"

telegram:
  token: "Не разевай роток на чужой токен"
