basePath: /v1
definitions:
  entity.User:
    properties:
      id:
        type: integer
      telegram_username:
        type: string
      username:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.userCreateForm:
    properties:
      telegram_username:
        type: string
      username:
        type: string
    required:
    - telegram_username
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a user service
  title: Go Clean Template API
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: Get all users
      operationId: user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create new user
      operationId: user_create
      parameters:
      - description: User Create Form
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.userCreateForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: New User
      tags:
      - user
  /user/:username:
    get:
      consumes:
      - application/json
      description: Get user by username
      operationId: user_by_username
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
      summary: User
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Update user
      operationId: user_update
      parameters:
      - in: query
        name: telegramUsername
        type: string
      - in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Update User
      tags:
      - user
swagger: "2.0"
